"""TON 首次研究数据 (由 Cowork 搜索引擎直接生成, 不依赖本地 Claude CLI)。

当本地 CLI 不可用时, 可以用此脚本直接生成报告。
"""
from __future__ import annotations
from datetime import datetime, timezone


def get_ton_research_data() -> dict:
    """返回 2026-05-06 搜集的 TON 研究数据。"""
    now = datetime.now(timezone.utc)
    return {
        "project": "TON",
        "token": "TON",
        "started_at": now.isoformat(),
        "completed_at": now.isoformat(),
        "duration_seconds": 180,
        "agents_ok": 5,
        "agents_total": 5,
        "agents": {
            # ── GitHub Agent ──
            "github": {
                "project": "TON",
                "github_orgs": ["ton-blockchain", "ton-org", "ton-community"],
                "main_repos": [
                    {"repo": "ton-blockchain/ton", "stars": 3700, "forks": 1100,
                     "last_commit_days_ago": 6, "contributors": 150,
                     "language": "C++", "description": "Main TON monorepo - 核心区块链实现"},
                    {"repo": "ton-blockchain/TEPs", "stars": 280, "forks": 120,
                     "last_commit_days_ago": 14, "contributors": 45,
                     "language": "Markdown", "description": "TON Enhancement Proposals"},
                    {"repo": "ton-org/blueprint", "stars": 350, "forks": 90,
                     "last_commit_days_ago": 3, "contributors": 30,
                     "language": "TypeScript", "description": "TON 智能合约开发框架"},
                    {"repo": "ton-community/awesome-ton", "stars": 357, "forks": 59,
                     "last_commit_days_ago": 7, "contributors": 40,
                     "language": "Markdown", "description": "TON 生态资源汇总"},
                    {"repo": "ton-org/ton-core", "stars": 310, "forks": 85,
                     "last_commit_days_ago": 10, "contributors": 25,
                     "language": "TypeScript", "description": "TON 核心 JS/TS SDK"},
                    {"repo": "ton-blockchain/wallet-contract", "stars": 180, "forks": 65,
                     "last_commit_days_ago": 20, "contributors": 15,
                     "language": "FunC", "description": "TON 钱包智能合约"},
                ],
                "notable_recent_prs": [
                    {"title": "Catchain 2.0 consensus upgrade", "repo": "ton-blockchain/ton",
                     "date": "2026-04-15", "significance": "区块生成时间从 10s 降至 ~400ms"},
                    {"title": "TON Teleport Bridge progress", "repo": "ton-blockchain/ton",
                     "date": "2026-04-28", "significance": "无信任 BTC 跨链桥开发中"},
                    {"title": "Tolk Dev Tools v2", "repo": "ton-org/blueprint",
                     "date": "2026-05-01", "significance": "新开发者工具包, 简化合约部署"},
                ],
                "dev_activity_score": 78,
                "dev_trend": "rising",
                "key_findings": [
                    "Catchain 2.0 于 2026 年 4 月上线, 区块时间 10s → 400ms, 性能提升 25 倍",
                    "TON Teleport Bridge (无信任 BTC 桥) 预计 2026 年中上线",
                    "3 个 GitHub 组织共维护 50+ 活跃仓库, 开发者工具链趋于成熟",
                    "Tolk/FunC/Tact 三种智能合约语言并存, 降低开发门槛",
                    "Q2 2026 推出 AppKit 新开发者工具, 吸引更多 dApp 开发者",
                ],
                "risks": [
                    "主仓库 3.7K stars 在 L1 公链中偏低 (Solana 12K, Ethereum 47K)",
                    "核心代码以 C++ 为主, 限制了社区贡献者参与门槛",
                    "CertiK 审计发现 Tact 语言存在潜在安全漏洞",
                ],
            },

            # ── Onchain Agent ──
            "onchain": {
                "project": "TON",
                "token_symbol": "TON",
                "price_usd": 1.98,
                "market_cap_billion": 5.0,
                "price_change_30d_pct": -8.5,
                "ath_usd": 8.25,
                "ath_drawdown_pct": -76.0,
                "daily_active_addresses": 155000,
                "daily_transactions": 2160000,
                "total_wallets_million": 52.1,
                "tvl_million": 59.15,
                "tvl_change_30d_pct": -12.3,
                "top_defi_protocols": [
                    {"name": "STON.fi", "tvl_million": 22.5, "category": "DEX"},
                    {"name": "DeDust", "tvl_million": 14.8, "category": "DEX"},
                    {"name": "Bemo", "tvl_million": 8.2, "category": "Liquid Staking"},
                    {"name": "Storm Trade", "tvl_million": 5.1, "category": "Perp DEX"},
                    {"name": "Evaa Protocol", "tvl_million": 3.8, "category": "Lending"},
                ],
                "staking_yield_pct": 3.8,
                "inflation_rate_pct": 0.6,
                "supply_circulating_billion": 2.5,
                "supply_total_billion": 5.1,
                "onchain_health_score": 58,
                "key_findings": [
                    "日交易 216 万笔, 在 L1 中活跃度较高",
                    "TVL 从 2024 年 7 月峰值 $742M 跌至 $59M, 下降 92%",
                    "52.1M 激活钱包, 得益于 Telegram 生态整合",
                    "通胀率仅 0.6%, 且有费用销毁机制 (燃烧 50% 手续费)",
                    "当前价格距 ATH 下跌 76%, 处于深度回调区间",
                ],
                "risks": [
                    "TVL $59M 极低, DeFi 生态远未成熟",
                    "鲸鱼持仓集中, 大户可引发短期剧烈波动",
                    "日活地址数据存在争议 (10 万 vs 50 万不同口径)",
                ],
            },

            # ── Narrative Agent ──
            "narrative": {
                "project": "TON",
                "narratives": ["L1 公链", "Telegram 生态", "Mass Adoption", "超级App入口", "BTC 跨链"],
                "narrative_heat": 72,
                "community_metrics": {
                    "twitter_followers": "1.5M",
                    "telegram_members": "800K+",
                    "reddit_subscribers": "35K",
                    "discord_members": "85K",
                },
                "sentiment": "neutral_to_bullish",
                "kol_opinions": [
                    {"who": "Coinpedia", "opinion": "TON 守住 $1.25 关键支撑, $1.50-$1.60 是突破区域, 若动能持续 2026 可达 $10",
                     "stance": "bullish"},
                    {"who": "CryptoTimes", "opinion": "Telegram 接管 TON 基金会, 短期暴涨 26%, 但缺乏明确催化剂, 可能回调",
                     "stance": "neutral"},
                    {"who": "CoinCodex", "opinion": "技术指标中性, 多头和空头在 $1.40-$1.62 拉锯, 鲸鱼抛压是主要风险",
                     "stance": "neutral_to_bearish"},
                    {"who": "BitcoinWorld", "opinion": "图表走势与 2023 年上涨前形态相似, 暗示可能有 185% 的涨幅",
                     "stance": "bullish"},
                ],
                "recent_catalysts": [
                    {"event": "Telegram 宣布接管 TON 基金会, Durov 称将成为最大验证者",
                     "date": "2026-05-05", "impact": "positive"},
                    {"event": "Catchain 2.0 上线, 区块时间降至 400ms",
                     "date": "2026-04-15", "impact": "positive"},
                    {"event": "Telegram 手续费降低 6 倍",
                     "date": "2026-05-05", "impact": "positive"},
                    {"event": "TON 24h 暴涨 26% 至 $1.73",
                     "date": "2026-05-05", "impact": "positive"},
                ],
                "upcoming_catalysts": [
                    {"event": "TON Teleport Bridge (无信任 BTC 跨链桥)",
                     "expected_date": "2026-Q3", "potential_impact": "high"},
                    {"event": "AppKit & Tolk Dev Tools 发布",
                     "expected_date": "2026-Q2", "potential_impact": "medium"},
                    {"event": "TON Pay 2.0 支付协议升级",
                     "expected_date": "2026-Q2", "potential_impact": "medium"},
                    {"event": "Telegram mini-app 生态大规模扩展",
                     "expected_date": "2026-H2", "potential_impact": "high"},
                ],
                "competitive_position": "TON 凭借 Telegram 10 亿用户的独特优势在 L1 公链中占据 Mass Adoption 赛道, 但在 DeFi TVL、开发者数量上远落后于 Ethereum、Solana、Base。Catchain 2.0 让性能达到行业领先水平 (400ms 出块), 但生态丰富度仍需时间培育",
                "community_score": 75,
                "key_findings": [
                    "Telegram 直接接管 TON 开发, 短期强烈利好但长期中心化风险",
                    "社区规模大 (Telegram 80 万+) 但活跃开发者相对少",
                    "5 月 5 日暴涨 26% 是放量突破, 但需观察成交量能否持续 $400M+",
                ],
                "risks": [
                    "Telegram 控制 = 中心化, 与区块链去中心化精神矛盾",
                    "Pavel Durov 个人法律/监管风险直接影响 TON",
                    "Tap-to-earn 项目 (Notcoin, Hamster Kombat) 退潮, 用户留存存疑",
                ],
            },

            # ── Risk Agent ──
            "risk": {
                "project": "TON",
                "risk_matrix": {
                    "smart_contract_risk": {"level": "medium", "score": 48,
                        "detail": "CertiK 审计发现 Tact 语言漏洞; FunC 较成熟但生态合约数量少"},
                    "centralization_risk": {"level": "high", "score": 78,
                        "detail": "Telegram 成为最大验证者 + 接管基金会, 高度中心化"},
                    "regulatory_risk": {"level": "high", "score": 72,
                        "detail": "Durov 曾被法国拘留; Telegram 在多国面临监管压力"},
                    "market_risk": {"level": "high", "score": 68,
                        "detail": "距 ATH 跌 76%, 鲸鱼集中, 波动性大; TVL 仅 $59M"},
                    "competition_risk": {"level": "medium", "score": 55,
                        "detail": "L1 赛道拥挤 (ETH/SOL/Base/SUI), 但 Telegram 入口独特"},
                    "tokenomics_risk": {"level": "low", "score": 30,
                        "detail": "0.6% 通胀 + 费用销毁; 初始供应已全部解锁, 无大额 unlock"},
                    "team_risk": {"level": "medium", "score": 52,
                        "detail": "核心团队强 (Durov + Telegram 工程师), 但过度依赖单一实体"},
                },
                "overall_risk_score": 58,
                "risk_level": "medium",
                "whale_concentration": "初始 49.2 亿 TON 已全部解锁。大户持仓集中, Top 100 地址持有约 40% 供应量。Telegram 自身将成为最大验证者和持有者",
                "key_risks": [
                    "Telegram 中心化控制 — 单一实体控制基金会 + 最大验证者 + 主要开发, 违背去中心化原则",
                    "Durov 个人风险 — 法律/监管事件可直接冲击 TON 价格和生态",
                    "DeFi TVL 断崖式下跌 — 从 $742M 降至 $59M, 生态活力存疑",
                    "鲸鱼抛压 — 大户持仓集中, 可引发闪崩",
                ],
                "mitigants": [
                    "Telegram 10 亿用户基础 = 巨大潜在用户池",
                    "Catchain 2.0 性能达到行业领先",
                    "低通胀 + 费用销毁提供通缩支撑",
                    "初始供应已全部解锁, 无悬崖式 unlock 风险",
                    "TON Teleport Bridge 若成功可带来 BTC 流动性",
                ],
                "worst_case_scenario": "Durov 再次遭遇法律困境导致 Telegram 运营中断, TON 生态崩溃; 或 Telegram 放弃 TON (如 2020 年), 代币归零风险。DeFi TVL 继续缩水至 <$20M, mini-app 用户流失",
                "black_swan_risks": [
                    "Telegram 被多国禁止运营 (如俄罗斯曾短暂禁止)",
                    "智能合约大规模漏洞导致 DeFi 协议被盗",
                    "监管机构认定 TON 为证券",
                ],
            },

            # ── Alpha Agent ──
            "alpha": {
                "project": "TON",
                "token": "TON",
                "verdict": "CAUTIOUS_BUY",
                "confidence": 58,
                "alpha_signals": [
                    {"signal": "Telegram 接管 TON 基金会 — 短期强催化剂, 24h 涨 26%",
                     "direction": "bullish", "strength": "strong",
                     "timeframe": "1-3个月", "source": "Narrative Agent"},
                    {"signal": "Catchain 2.0 性能突破 (400ms 出块) — 技术面利好",
                     "direction": "bullish", "strength": "moderate",
                     "timeframe": "3-6个月", "source": "GitHub Agent"},
                    {"signal": "TVL 从 $742M 暴跌至 $59M — DeFi 生态严重萎缩",
                     "direction": "bearish", "strength": "strong",
                     "timeframe": "6-12个月", "source": "Onchain Agent"},
                    {"signal": "价格距 ATH 跌 76% — 深度回调提供入场机会",
                     "direction": "bullish", "strength": "moderate",
                     "timeframe": "6-12个月", "source": "Onchain Agent"},
                    {"signal": "中心化风险: Telegram 单一实体控制整个生态",
                     "direction": "bearish", "strength": "moderate",
                     "timeframe": "长期", "source": "Risk Agent"},
                    {"signal": "TON Teleport Bridge 即将上线 — 可引入 BTC 流动性",
                     "direction": "bullish", "strength": "moderate",
                     "timeframe": "3-6个月", "source": "GitHub Agent"},
                ],
                "price_levels": {
                    "current": 1.98,
                    "support_1": 1.50,
                    "support_2": 1.25,
                    "resistance_1": 2.50,
                    "resistance_2": 3.50,
                    "target_6m": 3.00,
                    "stop_loss": 1.15,
                },
                "position_sizing": "建议仓位占 crypto portfolio 的 2-4%, 考虑到中心化风险不宜重仓",
                "entry_strategy": "分 3 批建仓: 当前价位 ($1.98) 建 40% 底仓; 回踩 $1.50 加 30%; 回踩 $1.25 加最后 30%。若直接突破 $2.50 则追涨 50% 仓位",
                "exit_triggers": [
                    "止盈: 达到 $3.00 (目标价) 减仓 50%, 达到 $3.50 清仓",
                    "止损: 跌破 $1.15 (前低) 全部止损",
                    "Telegram 宣布放弃 TON 或 Durov 遭遇重大法律问题立即清仓",
                    "DeFi TVL 跌破 $30M 且无回升迹象则减仓至 1%",
                ],
                "dimension_scores": {
                    "development": 78,
                    "onchain": 58,
                    "narrative": 72,
                    "risk_adjusted": 52,
                },
                "overall_score": 65,
                "executive_summary": "TON 凭借 Telegram 10 亿用户的独特入口优势, 以及 Catchain 2.0 性能突破, 在 L1 赛道中具备差异化竞争力。但 DeFi TVL 暴跌 92% 暴露生态空心化问题, 且 Telegram 高度中心化控制带来单点风险。当前价格距 ATH 跌 76% 提供了风险收益比尚可的入场机会, 建议谨慎建仓、严格止损。",
                "bull_case": "Telegram 全力推动 TON, mini-app 生态爆发, TVL 回升至 $500M+, TON Teleport Bridge 成功引入 BTC 流动性, 价格回升至 $3-5 区间 (50-150% 涨幅)",
                "bear_case": "Telegram 生态 mini-app 热度消退, DeFi TVL 继续萎缩至 <$30M, Durov 监管风波再起, 价格回落至 $1.00-1.25 (下跌 35-50%)",
                "catalysts_to_watch": [
                    "TON Teleport Bridge 上线日期及 BTC 跨链量",
                    "Telegram 手续费调整后的日交易量变化",
                    "DeFi TVL 是否出现拐点回升",
                    "Durov 相关监管/法律动态",
                    "下一波 Telegram mini-app 是否能带来真实用户留存",
                ],
                "comparable_projects": [
                    {"name": "SOL", "why_comparable": "同为高性能 L1, 均有强生态支持 (TON=Telegram, SOL=FTX后社区)",
                     "relative_valuation": "TON 市值 $5B vs SOL $80B+, TON 估值更低但生态更弱"},
                    {"name": "SUI", "why_comparable": "新一代 L1, 高 TPS, 类似发展阶段",
                     "relative_valuation": "SUI 市值 $10B+, TVL 更高, TON 有用户优势但 DeFi 不足"},
                    {"name": "NEAR", "why_comparable": "同样主打 Mass Adoption 和低门槛用户体验",
                     "relative_valuation": "NEAR 市值 $3-4B, 类似体量, 但 TON 有 Telegram 护城河"},
                ],
            },
        },
    }
